### PR TITLE
Created an iClicker page

### PR DESCRIPTION
**Pull request by mitch12**
Created the iClicker landing page, and related question page. Added some
stock images for the iClicker page as well.

### CODE REVIEW

**Comment by xcompass** [comment]
@mitch12 I pushed a fix. Could you do a rebase and update your PR. That should fix the issue of outdated deployment.

**Comment by xcompass** [comment]
@mitch12 Thanks for the rebase. The review instance is available now. 

Question for you, who request this change? The reviewer should be the one who request the change. Not @lenglund . As she has no context and can't sign off the update.

**Review by xcompass — APPROVED** [review]

**Comment by mitch12** [comment]
@xcompass thanks! Looks good on my end. And Melissa Lee (she works with Nancy and Bruce) requested this, but she does not have a GitHub account yet, I will help her set up one tomorrow. This is why I was not able to assign any reviewers to this PR.

**Comment by xcompass** [comment]
OK. Thanks. So you didn't add Letitia to the reviewer? Might be Github auto suggestion. If that's the case, never mind my previous comments.

**Comment by mitch12** [comment]
No I did not add Letitia. 

Thanks

**Comment by xcompass** [comment]
@mitch12 did you find someone to review and sign off the change?

**Comment by mitch12** [comment]
Yes, Melissa Lee. I am just waiting on her to make her GitHub account and send me her username so I can add her as a reviewer.

**Comment by xcompass** [comment]
Great. Let me know if you have any question.

**Comment by mitch12** [comment]
@xcompass , I can't seem to add Melissa as a reviewer (there is no option to). Could this be that she is not a contributing member for the ubc/DSpace repository?  Her Github account name is leem44.

**Comment by xcompass** [comment]
It seems she has to be a collaborator. I just invited her. Once she accepts, you should be able to add her.

**Comment by mitch12** [comment]
@xcompass  Melissa says she hasn't received an email invitation to be a collaborator yet (if it helps, her email that she signed up with is melissa.lee@stat.ubc.ca). Additionally, Dennis and I both don't seem to have permission to add reviewers. At most it seems we can just @mention people and then they can comment on whether or not to go ahead with the build, will that suffice for now?

**Comment by xcompass** [comment]
I've invited all three of your as a collaborator to this repo. Once accepted, you should be able to request the reviewer. Let me know if there is any problem.

**Comment by denfo** [comment]
Hey Pan, we are still unable to find a way to request a reviewer.

**Comment by xcompass** [comment]
how about now?

**Comment by denfo** [comment]
It works now!!!

**Pull request merged**
