### PR TITLE
Improved layout of images, improved layout of sim page, updated content

### PR DESCRIPTION
**Pull request by mitch12**
Improved the look of the home page. Improved the look and layout of the
sim-example page. Added grammatical content advised by Melissa.

### CODE REVIEW

**Comment by mitch12** [comment]
Sorry for any confusion, I was having trouble properly re-basing and re-committing the last Pull Request, so I made this new branch. Same as before, @leem44 is the reviewer.

**Review by leem44 — CHANGES_REQUESTED** [review]
screen shot 2017-09-01 at 5 47 43 pm
screen shot 2017-09-01 at 5 47 53 pm

**Comment by mitch12** [comment]
Hey @leem44 , okay those changes have been implemented. Are the sizes of the boxes better on that page?

**Comment by leem44** [comment]
Hi @mitch12, sorry could we make them a bit bigger now? Somewhere in between what we had before and this?

**Comment by mitch12** [comment]
@leem44 okay, hopefully that size works for you. Let me know what you think!

**Review by leem44 — APPROVED** [review]

**Comment by leem44** [comment]
From Nancy: the box on the first resource (the coffee cup box) was a slight bit shorter than the other boxes. Also, the fonts seem to be different sizes in the different boxes - and the “Read more” buttons.

**Pull request merged**
