### PR TITLE
Removed password fields + updated PDFS

### PR DESCRIPTION
**Pull request by mitch12**
Commented out the password fields for the registration forms, and updated several PDFs as per Bruce's request

### CODE REVIEW

**Review by xcompass — CHANGES_REQUESTED** [review]
Have you tested after you made the change? User can't register because of the missing password.

**Comment by mitch12** [comment]
Unfortunately, I wasn't able to test because I am unsure of how to reach the page for registration because I am unable to navigate there with the Join button. How are you arriving at that page?

**Comment by xcompass** [comment]
You have to register as a new user first and get the email for the registration link.

**Comment by mitch12** [comment]
Okay, I signed up as a new user, but still I don't think i can access that page given that I would be testing it on my local machine.

**Comment by xcompass** [comment]
Were you able to get the email?

**Comment by mitch12** [comment]
No. I never received the email.

**Comment by xcompass** [comment]
Then maybe take a look at the database in the VM to see if you can find the token and build the URL yourself.  http://localhost:8080/register?token=TOKEN

**Comment by mitch12** [comment]
I did a little research on that, and I am still a little lost on how to go about building the URL myself.

**Comment by xcompass** [comment]
used an alternative method. no need this PR.

**Pull request closed without merging**
