### PR TITLE
Update "About" page

### PR DESCRIPTION
**Pull request by denfo**

### CODE REVIEW

**Comment by denfo** [comment]
Hey Pan, could you assign @mitch12 to review this change?

**Comment by xcompass** [comment]
Who did the request for this change? Do you need that person to review as well?

**Review by mitch12 — COMMENTED** [review]
Only thing that needs changing is that you should change the paragraph containing [(Skylight (LINK((https://skylight.science.ubc.ca/contact)) ] into an actual link.

**Comment by denfo** [comment]
Hey Peter, it's been done.

**Comment by mitch12** [comment]
Okay, looks good now @denfo

**Pull request merged**
