### PR TITLE
Added multiple iClicker landing pages, updated and added content to several others

### PR DESCRIPTION
**Pull request by mitch12**
Added landing pages for iClicker content, added pages for iClicker questions, added content and links to Melissa's content. Fixed general grammar issues.

### CODE REVIEW

**Comment by mitch12** [comment]
The reviewer for this is @leem44 .

Large number of changes in this edit:
 Fixed indenting and spacing in several files, added several new landing pages, modified several old pages. Had to re-commit WV-ChiSquarecontingencyanalysis after fixing conflicts with rebasing. 

Also @xcompass , can the landing page **sim-example.jsp** not be included in this merge? During the rebase it appears something went wrong so the formatting of the page is off.

**Comment by xcompass** [comment]
@mitch12 Could you change the PR title to reflect the change you made? It is easier to see when on the PR list view. When merging, it is either none or all. So if you want to exclude a file, you need to remove it from your PR.

@leem44 you can find the instance that includes this change by clicking on "Show all checks" -> review -> copy and past the URL to your browser.

**Comment by xcompass** [comment]
@leem44 Once you looked at the changes, you can either approve or leave comments for updates by clicking on "Files changed" tab -> "review changes" button

**Review by xcompass — APPROVED** [review]

**Comment by leem44** [comment]
feedback_aug14_ie1-1
feedback_aug14-ie1-2
feedback_aug14_ie-2-1

feedback_aug14-ie-2-2

feedback_aug14-ie3-1
feedback_aug14_ie-3-2

**Comment by mitch12** [comment]
@xcompass I've made some new commits to fix the changes Melissa wanted, but it looks like the statspace image isn't being built again and therefore no review instance is going to be deployed. This also occurred with Dennis's last update to his PR from this morning.

**Comment by xcompass** [comment]
@mitch12 sorry, there was an issue on the deployment platform yesterday and I disabled the job. Now it's enabled and the image should be build shortly. /cc @denfo

**Comment by leem44** [comment]
1.  Remove graphs on the Sample Question page when click on "See more" for "Hypothesis Test" and "Confidence Interval" pages 
2. "as questions to be adapted for use in guided in-class _activities_ or other instructor-supplied material" - links to wrong page, we don't have material for this "activities" link yet - could remove link in the meantime

**Comment by mitch12** [comment]
Okay @leem44 , those additional changes have been made.

**Comment by leem44** [comment]
"activities" link under "Suggested Uses" for sampling dist of the mean and Confidence intervals - remove link until material is uploaded on SS

**Comment by mitch12** [comment]
Okay all the requested changes have been made, I think this branch should be ready to merge @xcompass .

**Comment by xcompass** [comment]
@leem44 are you satisfy the changes? If everything looks good, could you approve the change by selecting "Files" tab and "Review changes" button (green one), then approve? Once you approve, I'll merge the change and it will become part of the official code.

**Review by leem44 — APPROVED** [review]

**Comment by xcompass** [comment]
This change has been deployed to production.

**Pull request merged**
